name: dart_periphery
version: 0.8.26
description:  >- 
  dart_periphery is a Dart port of the native c-periphery library for Linux Peripheral I/O (GPIO, LED, PWM, SPI, I2C, MMIO and Serial peripheral I/O).

homepage: https://github.com/pezi/dart_periphery
repository: https://github.com/pezi/dart_periphery
issue_tracker: https://github.com/pezi/dart_periphery/issues
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: ^1.1.2
  path: ^1.8.1
  process: ^4.2.4
  collection: ^1.15.0
  stack_trace: ^1.10.0

 
dev_dependencies:
  test: ^1.20.1
  lints: ^1.0.1
