name: dart_periphery
version: 0.9.2
description:  >- 
  dart_periphery is a Dart port of the native c-periphery library for Linux Peripheral I/O (GPIO, LED, PWM, SPI, I2C, MMIO and Serial peripheral I/O).

homepage: https://github.com/pezi/dart_periphery
repository: https://github.com/pezi/dart_periphery
issue_tracker: https://github.com/pezi/dart_periphery/issues
environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  ffi: ^2.0.1
  path: ^1.8.2
  process: ^4.2.4
  collection: ^1.16.0
  stack_trace: ^1.10.0
  meta: ^1.8.0

 
dev_dependencies:
  test: ^1.20.1
  lints: ^2.0.0
