name: dart_periphery
version: 0.9.21
description:  >- 
  dart_periphery is a Dart port of the native c-periphery library for Linux Peripheral I/O (GPIO, LED, PWM, SPI, I2C, MMIO, ADC and Serial peripheral I/O).

homepage: https://github.com/pezi/dart_periphery
repository: https://github.com/pezi/dart_periphery
issue_tracker: https://github.com/pezi/dart_periphery/issues
environment:
  sdk: '>=3.3.0  <4.0.0'

platforms:
  linux:  

dependencies:
  ffi: ^2.1.4
  path: ^1.9.1
  process: ^5.0.5
  collection: ^1.19.1
  stack_trace: ^1.12.1
  meta: ^1.16.0
  async: ^2.13.0
  archive: ^4.0.7

 
dev_dependencies:
  test: ^1.26.3
  lints: ^6.0.0
